"""sync_models

Revision ID: 960d5e468a09
Revises: a83f8d67f2d1
Create Date: 2026-05-01 17:13:47.456929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960d5e468a09'
down_revision: Union[str, None] = 'a83f8d67f2d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('motif_report', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('budget', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'budget')
    op.drop_column('applications', 'motif_report')
    # ### end Alembic commands ###
