"""add_missing_columns_and_status

Revision ID: 9d2cac8895bf
Revises: 
Create Date: 2026-04-25 22:35:31.759193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2cac8895bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('host_supervisor', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('supervisor_email', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('host_department', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('title_of_stay', sa.String(length=100), nullable=True))
    op.add_column('applications', sa.Column('research_axis', sa.String(length=50), nullable=True))
    op.add_column('applications', sa.Column('expected_outcomes', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('cancelled_requested_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('applications', 'cancelled_requested_at')
    op.drop_column('applications', 'expected_outcomes')
    op.drop_column('applications', 'research_axis')
    op.drop_column('applications', 'title_of_stay')
    op.drop_column('applications', 'host_department')
    op.drop_column('applications', 'supervisor_email')
    op.drop_column('applications', 'host_supervisor')
    # ### end Alembic commands ###
