"""Add AllowanceScale

Revision ID: ce5737ef237e
Revises: 2266ea78e302
Create Date: 2026-05-02 00:31:14.757220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5737ef237e'
down_revision: Union[str, None] = '2266ea78e302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowance_scales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_type', sa.Integer(), nullable=False),
    sa.Column('days1_10', sa.Integer(), nullable=False),
    sa.Column('days11_29_pkg', sa.Integer(), nullable=False),
    sa.Column('days11_29_day', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('fraction_pkg', sa.Integer(), nullable=False),
    sa.Column('fraction_day', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_type')
    )
    op.create_index(op.f('ix_allowance_scales_id'), 'allowance_scales', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allowance_scales_id'), table_name='allowance_scales')
    op.drop_table('allowance_scales')
    # ### end Alembic commands ###
