"""Add scoring fields

Revision ID: da737642bc1d
Revises: dc5bfbd26604
Create Date: 2026-05-12 12:56:01.247695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da737642bc1d'
down_revision: Union[str, None] = 'dc5bfbd26604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('prev_completed_count', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('last_stay_date', sa.Date(), nullable=True))
    op.alter_column('users', 'laboratory_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'laboratory_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('applications', 'last_stay_date')
    op.drop_column('applications', 'prev_completed_count')
    # ### end Alembic commands ###
