"""Add visa to document types

Revision ID: e350089f5f8e
Revises: da737642bc1d
Create Date: 2026-05-12 13:10:20.485544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e350089f5f8e'
down_revision: Union[str, None] = 'da737642bc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE documents_type ADD VALUE IF NOT EXISTS 'visa'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
